-- begin TIMETABLE_SERVICE
alter table TIMETABLE_SERVICE add constraint FK_TIMETABLE_SERVICE_ON_BUS foreign key (BUS_ID) references TIMETABLE_BUS(ID)^
create index IDX_TIMETABLE_SERVICE_ON_BUS on TIMETABLE_SERVICE (BUS_ID)^
-- end TIMETABLE_SERVICE
-- begin TIMETABLE_BUS
create unique index IDX_TIMETABLE_BUS_UNIQ_DRIVER_PHONE on TIMETABLE_BUS (DRIVER_PHONE)^
create unique index IDX_TIMETABLE_BUS_UNIQ_BUS_NUMBER on TIMETABLE_BUS (BUS_NUMBER)^
-- end TIMETABLE_BUS
